version: '3.8'

services:
  mlflow:
    image: bitnami/mlflow:2
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=sqlite:////tmp/mlflow.db
    volumes:
      - ./data/mlruns:/app/mlruns
    restart: always

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    restart: always
